# Generated by Django 2.2.7 on 2020-04-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200405_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesstatistic',
            name='cat_name',
            field=models.CharField(max_length=255),
        ),
    ]
