# Generated by Django 2.2.7 on 2020-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200405_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('max_price', models.BigIntegerField(default=0)),
                ('min_price', models.BigIntegerField(default=0)),
            ],
        ),
    ]
