# Generated by Django 2.2.7 on 2020-04-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_itemstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstatistic',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
