# Generated by Django 2.2.7 on 2020-04-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200407_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemstatistic',
            old_name='item_name',
            new_name='item',
        ),
    ]
