# Generated by Django 2.2.7 on 2020-04-08 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200408_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstatistic',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.History'),
        ),
    ]
