# Generated by Django 2.2.7 on 2020-04-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('item_id_plus_hue', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('item_id', models.CharField(max_length=255)),
                ('item_hue', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сategories', to='store.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_point_name', models.CharField(max_length=255)),
                ('vendor_x', models.CharField(max_length=255)),
                ('vendor_y', models.CharField(max_length=255)),
                ('vendor_z', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, null=True)),
                ('item_description', models.CharField(max_length=255, null=True)),
                ('item_total_price', models.CharField(max_length=255, null=True)),
                ('mapping_categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_mapping_categories', to='store.Mapping')),
                ('time_stamp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.History')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_vendor', to='store.Vendor')),
            ],
        ),
    ]
