# Generated by Django 2.2.7 on 2020-04-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_currentstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstatistic',
            name='total_vendors',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CategoriesStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=255)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сat_name', to='store.Categories')),
            ],
        ),
    ]
