# Generated by Django 2.2.7 on 2020-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200405_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='item_total_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
