# Generated by Django 2.2.7 on 2020-04-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_itemstatistic_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemstatistic',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_mapping_categories', to='store.ItemsLibrary'),
        ),
    ]
